name: qr_code_app
description: "A QR code app."
version: 1.2.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  image_picker: ^1.1.2
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  hive_flutter: ^1.1.0
  barcode_widget: ^2.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
